import { createFileRoute } from "@tanstack/react-router";
import { useQueryClient } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { useState } from "react";
import { toast } from "sonner";
import { Box, Plus, Tags } from "lucide-react";
import { PageHeader } from "@/components/app-shell";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { useActiveCompanyId, useMyContext, usePermissions } from "@/hooks/use-foundation";
import { usePricePolicies, useProducts } from "@/hooks/use-crm";
import { createPlan, createPricePolicy, createProduct } from "@/lib/crm.functions";

export const Route = createFileRoute("/_authenticated/catalogo")({
  head: () => ({ meta: [
    { title: "Catálogo comercial — IGA Network BR" },
    { name: "description", content: "Produtos, planos e políticas comerciais versionadas com vigência e alçadas." },
    { property: "og:title", content: "Catálogo comercial — IGA Network BR" },
    { property: "og:description", content: "Catálogo comercial governado e histórico de preços preservado." },
    { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" },
  ]}), component: Catalogo,
});

const money = (v: string | number) => Number(v).toLocaleString("pt-BR", { style: "currency", currency: "BRL" });

function Catalogo() {
  const companyId = useActiveCompanyId(); const { can } = usePermissions(companyId); const { data: me } = useMyContext();
  const { data: products, isLoading } = useProducts(companyId); const { data: policies } = usePricePolicies(companyId);
  const manage = can("product.manage") || !!me?.isPlatformAdmin; const priceManage = can("price_policy.manage") || !!me?.isPlatformAdmin;
  return <div><PageHeader title="Catálogo comercial" description="Produto, plano e política de preço são entidades separadas. Cada alteração de preço gera nova versão." />
    <div className="mb-4 flex flex-wrap justify-end gap-2">{manage ? <><NovoProduto companyId={companyId} /><NovoPlano companyId={companyId} products={products ?? []} /></> : null}{priceManage ? <NovaPolitica companyId={companyId} products={products ?? []} /> : null}</div>
    <div className="grid gap-4 lg:grid-cols-2">{(products ?? []).map((p) => <Card key={p.id}><CardHeader className="pb-3"><CardTitle className="flex items-center justify-between text-sm"><span className="flex items-center gap-2"><Box className="h-4 w-4 text-accent" />{p.name}</span><Badge variant="secondary">{p.status}</Badge></CardTitle><p className="text-xs text-muted-foreground"><span className="font-mono">{p.code}</span>{p.category ? ` · ${p.category}` : ""}</p></CardHeader><CardContent className="space-y-3"><p className="text-sm text-muted-foreground">{p.description ?? "Sem descrição."}</p>{((p.plans ?? []) as Array<{ id:string; code:string; name:string; status:string }>).map((pl) => { const pp = (policies ?? []).filter((x) => x.plan_id === pl.id); const current = pp.find((x) => x.status === "active") ?? pp[0]; return <div key={pl.id} className="rounded-md border p-3 text-sm"><div className="flex items-center justify-between"><span className="font-medium">{pl.name}</span><span className="font-mono text-xs text-muted-foreground">{pl.code}</span></div>{current ? <div className="mt-2 grid grid-cols-2 gap-2 text-xs text-muted-foreground"><span>Implantação: {money(current.setup_price)}</span><span>Mensalidade: {money(current.monthly_price)}</span><span>Versão {current.version}</span><span>Desconto até {current.max_discount_percent}%</span></div> : <p className="mt-1 text-xs text-muted-foreground">Sem política de preço vigente.</p>}</div>; })}</CardContent></Card>)}</div>
    {!products?.length ? <p className="text-sm text-muted-foreground">{isLoading ? "Carregando…" : "Nenhum produto cadastrado."}</p> : null}
  </div>;
}

function NovoProduto({ companyId }: { companyId: string | null }) { const fn=useServerFn(createProduct), qc=useQueryClient(); const [open,setOpen]=useState(false), [code,setCode]=useState(""), [name,setName]=useState(""), [desc,setDesc]=useState(""); async function save(){if(!companyId)return;try{await fn({data:{companyId,code,name,description:desc||undefined}});toast.success("Produto criado");setOpen(false);qc.invalidateQueries({queryKey:["products"]});}catch(e){toast.error((e as Error).message)}} return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button size="sm" variant="outline"><Plus className="mr-2 h-4 w-4"/>Produto</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Novo produto</DialogTitle><DialogDescription>Solução comercial que poderá ter um ou mais planos.</DialogDescription></DialogHeader><Label>Código</Label><Input value={code} onChange={e=>setCode(e.target.value)}/><Label>Nome</Label><Input value={name} onChange={e=>setName(e.target.value)}/><Label>Descrição</Label><Textarea value={desc} onChange={e=>setDesc(e.target.value)}/><DialogFooter><Button onClick={save} disabled={code.length<2||name.length<2}>Salvar</Button></DialogFooter></DialogContent></Dialog> }
function NovoPlano({ companyId, products }: { companyId:string|null; products:Array<{id:string;name:string}> }) { const fn=useServerFn(createPlan),qc=useQueryClient();const[open,setOpen]=useState(false),[product,setProduct]=useState(""),[code,setCode]=useState(""),[name,setName]=useState("");async function save(){if(!companyId)return;try{await fn({data:{companyId,productId:product,code,name}});toast.success("Plano criado");setOpen(false);qc.invalidateQueries({queryKey:["products"]});}catch(e){toast.error((e as Error).message)}}return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button size="sm" variant="outline"><Plus className="mr-2 h-4 w-4"/>Plano</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Novo plano</DialogTitle><DialogDescription>Plano comercial vinculado a um produto.</DialogDescription></DialogHeader><Select value={product} onValueChange={setProduct}><SelectTrigger><SelectValue placeholder="Produto"/></SelectTrigger><SelectContent>{products.map(p=><SelectItem key={p.id} value={p.id}>{p.name}</SelectItem>)}</SelectContent></Select><Label>Código</Label><Input value={code} onChange={e=>setCode(e.target.value)}/><Label>Nome</Label><Input value={name} onChange={e=>setName(e.target.value)}/><DialogFooter><Button onClick={save} disabled={!product||code.length<2||name.length<2}>Salvar</Button></DialogFooter></DialogContent></Dialog>}
function NovaPolitica({companyId,products}:{companyId:string|null;products:Array<{id:string;name:string;plans?:Array<{id:string;name:string}>}>}){const fn=useServerFn(createPricePolicy),qc=useQueryClient();const[open,setOpen]=useState(false),[product,setProduct]=useState(""),[plan,setPlan]=useState(""),[name,setName]=useState(""),[setup,setSetup]=useState("0"),[monthly,setMonthly]=useState("0"),[max,setMax]=useState("0"),[threshold,setThreshold]=useState("0");const plans=products.find(p=>p.id===product)?.plans??[];async function save(){if(!companyId)return;try{await fn({data:{companyId,productId:product,planId:plan,name,setupPrice:Number(setup),monthlyPrice:Number(monthly),maxDiscountPercent:Number(max),approvalThresholdPercent:Number(threshold),billingPeriod:"monthly"}});toast.success("Nova versão de preço criada");setOpen(false);qc.invalidateQueries({queryKey:["price-policies"]});}catch(e){toast.error((e as Error).message)}}return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button size="sm"><Tags className="mr-2 h-4 w-4"/>Política de preço</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Nova política de preço</DialogTitle><DialogDescription>Cria uma nova versão; preços históricos permanecem intactos.</DialogDescription></DialogHeader><Select value={product} onValueChange={v=>{setProduct(v);setPlan("")}}><SelectTrigger><SelectValue placeholder="Produto"/></SelectTrigger><SelectContent>{products.map(p=><SelectItem key={p.id} value={p.id}>{p.name}</SelectItem>)}</SelectContent></Select><Select value={plan} onValueChange={setPlan}><SelectTrigger><SelectValue placeholder="Plano"/></SelectTrigger><SelectContent>{plans.map(p=><SelectItem key={p.id} value={p.id}>{p.name}</SelectItem>)}</SelectContent></Select><Label>Nome da política</Label><Input value={name} onChange={e=>setName(e.target.value)}/><div className="grid grid-cols-2 gap-3"><div><Label>Implantação</Label><Input type="number" min="0" value={setup} onChange={e=>setSetup(e.target.value)}/></div><div><Label>Mensalidade</Label><Input type="number" min="0" value={monthly} onChange={e=>setMonthly(e.target.value)}/></div><div><Label>Desconto máximo (%)</Label><Input type="number" min="0" max="100" value={max} onChange={e=>setMax(e.target.value)}/></div><div><Label>Exige aprovação acima de (%)</Label><Input type="number" min="0" max="100" value={threshold} onChange={e=>setThreshold(e.target.value)}/></div></div><DialogFooter><Button onClick={save} disabled={!product||!plan||name.length<2}>Criar versão</Button></DialogFooter></DialogContent></Dialog>}
